config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock_in.rb
class ClockIn < Event

end

app/models/clock_out.rb
class ClockOut < Event

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  scope :today, -> { where('time >= ?', Time.zone.now.beginning_of_day) }
  scope :clock_in, -> { where(type: 'ClockIn') }
  scope :clock_out, -> { where(type: 'ClockOut') }

  before_create :set_time

  def set_time
    self.time = Time.zone.now if self.time.blank?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  enum role: [:teacher, :admin]
  after_initialize :set_default_role, :if => :new_record?
  before_create :set_default_role

  def set_default_role
    self.role ||= :teacher
  end

  def clock_in_today?
    self.events.today.clock_in.present?
  end

  def clock_out_today?
    self.events.today.clock_out.present?
  end

  def event_type
    if self.clock_out_today? && self.clock_in_today?
      self.events.order('updated_at ASC').try(:last).try(:type) == 'ClockOut' ? ClockIn : ClockOut
    elsif self.clock_in_today?
      ClockOut
    elsif self.clock_out_today?
      ClockIn
    elsif !self.clock_out_today? && !self.clock_in_today?
      ClockIn
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_account_update_params, if: :devise_controller?
  before_action :configure_sign_up_params, if: :devise_controller?

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
  end

  # GET /events/new
  def new
    @event = current_user.event_type.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_url, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_url, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :user_id, :type, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_clock.html.erb
<div id="liveclock" class="outer_face">

  <div class="marker oneseven"></div>
  <div class="marker twoeight"></div>
  <div class="marker fourten"></div>
  <div class="marker fiveeleven"></div>

  <div class="inner_face">
    <div class="hand hour"></div>
    <div class="hand minute"></div>
    <div class="hand second"></div>
  </div>

</div>


<script type="text/javascript">

    /***********************************************
     * CSS3 Analog Clock- by JavaScript Kit (www.javascriptkit.com)
     * Visit JavaScript Kit at http://www.javascriptkit.com/ for this script and 100s more
     ***********************************************/

    var $hands = $('#liveclock div.hand')

    window.requestAnimationFrame = window.requestAnimationFrame
        || window.mozRequestAnimationFrame
        || window.webkitRequestAnimationFrame
        || window.msRequestAnimationFrame
        || function(f){setTimeout(f, 60)}


    function updateclock(){
        var curdate = new Date()
        var hour_as_degree = ( curdate.getHours() + curdate.getMinutes()/60 ) / 12 * 360
        var minute_as_degree = curdate.getMinutes() / 60 * 360
        var second_as_degree = ( curdate.getSeconds() + curdate.getMilliseconds()/1000 ) /60 * 360
        $hands.filter('.hour').css({transform: 'rotate(' + hour_as_degree + 'deg)' })
        $hands.filter('.minute').css({transform: 'rotate(' + minute_as_degree + 'deg)' })
        $hands.filter('.second').css({transform: 'rotate(' + second_as_degree + 'deg)' })
        requestAnimationFrame(updateclock)
    }

    requestAnimationFrame(updateclock)


</script>

app/views/events/_form.html.erb
<%= form_for @event,url: (@event.new_record? ? events_path : event_path(@event)), as: :event, :html => { :class => "form-horizontal event" } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <% unless @event.new_record? %>
    <div class="form-group">
      <%= f.label :type, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.select :type, options_for_select([['Clock In', 'ClockIn'], ['Clock Out', 'ClockOut']]), :class => 'form-control' %>
      </div>
      <%=f.error_span(:type) %>
    </div>

    <div class="form-group">
      <%= f.label :time, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10 input-group date" style="padding: 0 14px;">
        <%= f.text_field :time, :class => 'form-control datetimepicker' , data: {format: "dd/MM/yyyy hh:mm:ss"} %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
      <%=f.error_span(:time) %>
    </div>
  <% else %>
    <%= f.hidden_field :type %>
  <% end %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
        $('.datetimepicker').datetimepicker({
            format: 'DD/MM/YYYY HH:mm:ss'
        });
</script>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<div class="col-xs-offset-5 col-sm-offset-5"><%= render 'clock' %></div>
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.type %></td>
        <td><%= event.time %></td>
        <td>
          <%#= link_to t('.show', :default => t("helpers.links.show")),
                      event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end unless @events.blank?%>
    <% if @events.blank? %>
      <tr>
        <td colspan="4" class="text-center">
          No records found
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t('.new_event', :default => t("helpers.links.new_event")),
            new_event_path,
            :class => 'btn btn-primary pull-right', style: 'color: #ffffff' %>

app/views/events/new.html.erb
<div class="col-xs-offset-5 col-sm-offset-5"><%= render 'clock' %></div>
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloacker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Cloacker', root_url , class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li class="active">
              <%= link_to 'Home', root_url %>
            </li>
        <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li> <%= link_to "Welcome #{current_user.name.present? ? current_user.name : 'Guest'}", edit_user_registration_path(current_user) %> </li>
            <li>
              <%= link_to 'Log Out', destroy_user_session_url, method: :delete %>
            </li>
          <% else %>
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>